language: node_js
node_js:
  - 5.7.1

# User container based travis infrastructure which allows caching
# features for open source projects.
sudo: false

script:
  - cd js
  - npm install
  - npm test

cache:
  directories:
    - node_modules